spring.output.ansi.enabled: ALWAYS

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console