spring.output.ansi.enabled: ALWAYS

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
spring:
  config:
    import: classpath:application-security.yml
  profiles:
    include:
      - security
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console